============================= test session starts ==============================
platform linux -- Python 3.12.3, pytest-8.3.4, pluggy-1.5.0
rootdir: /home/manyu/gdrive/Gittable/Code/math_problems_debate
configfile: pyproject.toml
plugins: Faker-28.4.1, anyio-4.8.0, asyncio-0.23.8, env-1.1.5, mock-3.14.0
asyncio: mode=Mode.STRICT
collected 12 items

tests/test_llm_utils.py ..........Fs                                     [100%]

=================================== FAILURES ===================================
_____ test_get_response_with_response_model_more_complicated[gpt-4o-mini] ______

llm_agent_sync = <solib.utils.llm_utils.LLM_Agent object at 0x7c4aa7f55c70>

    def test_get_response_with_response_model_more_complicated(llm_agent_sync):
        class ResponseModel(BaseModel):
            students: list[str] = Field(description="Each key is an ID, each value is a name.")
        ## dicts don't work
    
        prompt = "Create an object consisting of an attribute students, which is a dictionary of 5 students with IDs as keys and names as values."
        response = llm_agent_sync.get_response_sync(prompt=prompt, response_model=ResponseModel)
        assert isinstance(response, ResponseModel)
        assert len(response.students) == 5
>       assert all(isinstance(key, int) and isinstance(value, str) for key, value in response.students.items())
E       AttributeError: 'list' object has no attribute 'items'

tests/test_llm_utils.py:143: AttributeError
=============================== warnings summary ===============================
.venv/lib/python3.12/site-packages/pydantic/_internal/_config.py:295
.venv/lib/python3.12/site-packages/pydantic/_internal/_config.py:295
  /home/manyu/gdrive/Gittable/Code/math_problems_debate/.venv/lib/python3.12/site-packages/pydantic/_internal/_config.py:295: PydanticDeprecatedSince20: Support for class-based `config` is deprecated, use ConfigDict instead. Deprecated in Pydantic V2.0 to be removed in V3.0. See Pydantic V2 Migration Guide at https://errors.pydantic.dev/2.10/migration/
    warnings.warn(DEPRECATION_MESSAGE, DeprecationWarning)

.venv/lib/python3.12/site-packages/pydantic/_internal/_config.py:345
  /home/manyu/gdrive/Gittable/Code/math_problems_debate/.venv/lib/python3.12/site-packages/pydantic/_internal/_config.py:345: UserWarning: Valid config keys have changed in V2:
  * 'fields' has been removed
    warnings.warn(message, UserWarning)

.venv/lib/python3.12/site-packages/litellm/utils.py:160
  /home/manyu/gdrive/Gittable/Code/math_problems_debate/.venv/lib/python3.12/site-packages/litellm/utils.py:160: DeprecationWarning: open_text is deprecated. Use files() instead. Refer to https://importlib-resources.readthedocs.io/en/latest/using.html#migrating-from-legacy for migration advice.
    with resources.open_text(

tests/test_llm_utils.py::test_get_response_async_returns_string[gpt-4o-mini]
tests/test_llm_utils.py::test_get_probs_async_returns_dict[gpt-4o-mini]
tests/test_llm_utils.py::test_get_response_async_with_max_tokens[gpt-4o-mini]
tests/test_llm_utils.py::test_get_response_async_with_words_in_mouth[gpt-4o-mini]
tests/test_llm_utils.py::test_get_response_async_with_response_model[gpt-4o-mini]
  /usr/lib/python3.12/asyncio/base_events.py:712: RuntimeWarning: coroutine 'Logging.async_success_handler' was never awaited
    self._ready.clear()
  Enable tracemalloc to get traceback where the object was allocated.
  See https://docs.pytest.org/en/stable/how-to/capture-warnings.html#resource-warnings for more info.

tests/test_llm_utils.py::test_get_response_async_with_response_model_more_complicated[gpt-4o-mini]
  /home/manyu/gdrive/Gittable/Code/math_problems_debate/.venv/lib/python3.12/site-packages/_pytest/python.py:148: PytestUnhandledCoroutineWarning: async def functions are not natively supported and have been skipped.
  You need to install a suitable plugin for your async framework, for example:
    - anyio
    - pytest-asyncio
    - pytest-tornasync
    - pytest-trio
    - pytest-twisted
    warnings.warn(PytestUnhandledCoroutineWarning(msg.format(nodeid)))

-- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
=========================== short test summary info ============================
FAILED tests/test_llm_utils.py::test_get_response_with_response_model_more_complicated[gpt-4o-mini]
============ 1 failed, 10 passed, 1 skipped, 10 warnings in 26.20s =============
